FROM nginx:alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY login/ /usr/share/nginx/html/login/
COPY registration/ /usr/share/nginx/html/registration/
COPY user/ /usr/share/nginx/html/user/
